#!/usr/bin/env python3
"""
Keryx 2.5 — launcher icon generator.

Single source for the adaptive icon layers AND the legacy API 24/25 rasters, so
the two can never drift.  Run:  python3 Hermes-Chat/tools/launcher_icon.py

WHY THIS REPLACED THE BEZIER GENERATOR
--------------------------------------
Until 2.5 the launcher art came from tools/kerykeion_icon.py, which plotted the
kerykeion as constant-width, round-capped monoline strokes.  That geometry was
exact and symmetrical and it looked like clip art — Jonny, on device: "those
look drawn by little kids".  The failure was structural, not a matter of
tuning: a real mark needs tapered bodies, a shaped serpent head and wings with
internal structure, which is filled-form work rather than traced lines.

So the art is now a raster mark (tools/icon_source/keryx-mark.png), and this
script does everything downstream of it deterministically.  kerykeion_icon.py
survives, but ONLY as the source of the 24dp notification glyph — see its
header.  Nothing writes the launcher art but this file.

WHAT IT DOES
------------
The source is a flat matte-void square with the mark centred.  Android wants
the mark on transparency, scaled inside the 66dp safe circle of the 108dp
adaptive canvas, so:

  1. key the near-black ground out to alpha
  2. crop to the mark, scale so its longest side fits SAFE of the canvas
  3. emit the foreground PNGs, the monochrome silhouette, and the legacy
     rounded-square / circular rasters

Edge fringe from the key lands on a near-black background layer, where it is
invisible by construction.
"""

import os
from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "..", "app", "src", "main", "res")
SOURCE = os.path.join(HERE, "icon_source", "keryx-mark.png")

VOID = (0x0B, 0x0A, 0x12)

# Fraction of the 108dp adaptive canvas the mark may occupy. The safe circle is
# 66/108 = 0.611; we sit just inside it so a circular mask never clips a wingtip.
SAFE = 0.60

# Keying thresholds against the flat ground. Below FLOOR is background, above
# FLOOR+RAMP is solid mark; between is the antialiased edge.
FLOOR, RAMP = 52, 70

# (density, legacy px, adaptive foreground px) — the legacy 108dp canvas maps
# onto a 72dp visible window, hence the two different sizes.
DENSITIES = [("mdpi", 48, 108), ("hdpi", 72, 162), ("xhdpi", 96, 216),
             ("xxhdpi", 144, 324), ("xxxhdpi", 192, 432)]

SS = 4  # supersample for the mask edges, downscaled with LANCZOS


def keyed_mark():
    """The source mark, background keyed to alpha, cropped to its own bounds."""
    im = Image.open(SOURCE).convert("RGB")
    w, h = im.size
    px = im.load()
    a = Image.new("L", (w, h), 0)
    ap = a.load()
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            v = max(r, g, b)
            ap[x, y] = 0 if v < FLOOR else min(255, int((v - FLOOR) * 255 / RAMP))
    out = im.copy()
    out.putalpha(a)
    box = a.point(lambda v: 255 if v > 24 else 0).getbbox()
    return out.crop(box)


def fitted(mark, canvas_px, safe=SAFE):
    """[mark] scaled to occupy `safe` of a `canvas_px` square, centred, on transparency."""
    target = canvas_px * safe
    s = min(target / mark.width, target / mark.height)
    m = mark.resize((max(1, round(mark.width * s)), max(1, round(mark.height * s))), Image.LANCZOS)
    out = Image.new("RGBA", (canvas_px, canvas_px), (0, 0, 0, 0))
    out.paste(m, ((canvas_px - m.width) // 2, (canvas_px - m.height) // 2), m)
    return out


def silhouette(rgba):
    """White-on-transparent silhouette — what the themed-icon layer is tinted from."""
    a = rgba.getchannel("A")
    out = Image.new("RGBA", rgba.size, (255, 255, 255, 0))
    out.putalpha(a)
    return out


def legacy(mark, size, shape):
    """Pre-adaptive icon: the mark on the void, masked to a rounded square or a circle."""
    S = size * SS
    base = Image.new("RGBA", (S, S), VOID + (255,))
    # The legacy window is 72dp of the 108dp canvas, so the mark reads larger here.
    fg = fitted(mark, S, safe=SAFE * 108 / 72)
    base.paste(fg, (0, 0), fg)
    m = Image.new("L", (S, S), 0)
    d = ImageDraw.Draw(m)
    if shape == "round":
        d.ellipse([0, 0, S - 1, S - 1], fill=255)
    else:
        d.rounded_rectangle([0, 0, S - 1, S - 1], radius=int(S * 0.235), fill=255)
    out = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    out.paste(base, (0, 0), m)
    return out.resize((size, size), Image.LANCZOS)


def write_adaptive_xml():
    xml = ('<?xml version="1.0" encoding="utf-8"?>\n'
           '<!-- GENERATED by Hermes-Chat/tools/launcher_icon.py — do not hand-edit. -->\n'
           '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
           '    <background android:drawable="@drawable/ic_launcher_background" />\n'
           '    <foreground android:drawable="@mipmap/ic_launcher_foreground" />\n'
           '    <monochrome android:drawable="@mipmap/ic_launcher_monochrome" />\n'
           '</adaptive-icon>\n')
    for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
        p = os.path.join(RES, "mipmap-anydpi-v26", name)
        with open(p, "w") as fh:
            fh.write(xml)
        print("wrote", os.path.relpath(p, RES))


def main():
    mark = keyed_mark()
    print(f"mark keyed: {mark.size[0]}x{mark.size[1]}")
    for dens, legacy_px, fg_px in DENSITIES:
        d = os.path.join(RES, f"mipmap-{dens}")
        os.makedirs(d, exist_ok=True)
        fg = fitted(mark, fg_px)
        fg.save(os.path.join(d, "ic_launcher_foreground.png"))
        silhouette(fg).save(os.path.join(d, "ic_launcher_monochrome.png"))
        legacy(mark, legacy_px, "square").save(os.path.join(d, "ic_launcher.png"))
        legacy(mark, legacy_px, "round").save(os.path.join(d, "ic_launcher_round.png"))
        print(f"wrote mipmap-{dens}: {fg_px}px foreground + monochrome, {legacy_px}px legacy pair")
    write_adaptive_xml()

    # The vector foreground/monochrome are gone; leaving them would let a stale
    # @drawable/… reference resurrect the old mark.
    for stale in ("drawable/ic_launcher_foreground.xml", "drawable/ic_launcher_monochrome.xml"):
        p = os.path.join(RES, stale)
        if os.path.exists(p):
            os.remove(p)
            print("removed stale", stale)


if __name__ == "__main__":
    main()
