package chat.keryx.app

import chat.keryx.core.model.CronDeltaCalc
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The diff feed's promise is "what this report says that the last one didn't". These pin the
 * shapes that would betray it: a date stamp is not news, a moved number IS news (as an
 * update, not a gone-and-new pair), chrome never counts, and an unchanged report says so.
 */
class CronDeltaTest {

    private val monday = """
        # Daily Brief — 2026-09-01 07:15
        [IMPORTANT: generated by the runner]
        ## Inbox
        - 3 PRs open on hermes-agent, oldest is #77994
        - Salt Creek meeting notes filed
        ## Calendar
        - Dentist Thursday 14:00
        ---
        Done.
    """.trimIndent()

    private val tuesday = """
        # Daily Brief — 2026-09-02 07:15
        [IMPORTANT: generated by the runner]
        ## Inbox
        - 5 PRs open on hermes-agent, oldest is #77994
        - **ATX Infusion**: week 1 scroll went out
        ## Calendar
        - Dentist Thursday 14:00
        ---
        Done.
    """.trimIndent()

    @Test
    fun `a date stamp alone is not a change`() {
        val d = CronDeltaCalc.compute(monday, monday.replace("2026-09-01", "2026-09-02"))
        assertTrue(d.same)
        assertEquals("same as last run", d.summary)
        assertNull(d.badge)
    }

    @Test
    fun `new lines, moved numbers and gone lines are told apart`() {
        val d = CronDeltaCalc.compute(monday, tuesday)
        assertEquals(listOf("ATX Infusion: week 1 scroll went out"), d.added)
        assertEquals(listOf("5 PRs open on hermes-agent, oldest is #77994"), d.updated)
        assertEquals(listOf("Salt Creek meeting notes filed"), d.removed)
        assertEquals("+1 new · 1 updated · 1 gone", d.summary)
        assertEquals("+1", d.badge)
    }

    @Test
    fun `headings, rules, machine lines and short chatter never make news`() {
        val d = CronDeltaCalc.compute(
            "## Inbox\n- Nothing new today\n---\nDone.",
            "## Inbox\n- Nothing new today\n[IMPORTANT: x]\n====\nOk.",
        )
        // "Done." → "Ok." differ but are under the news threshold; the headings match.
        assertTrue(d.same)
    }

    @Test
    fun `an unchanged report is mostly carried over`() {
        val d = CronDeltaCalc.compute(monday, monday)
        assertTrue(d.same)
        assertEquals(1f, d.carryOver, 0.0001f)
    }

    @Test
    fun `an entirely new report carries nothing over`() {
        val d = CronDeltaCalc.compute("- the old world was quiet today", "- a brand new topic entirely, unrelated words")
        assertEquals(1, d.added.size)
        assertEquals(1, d.removed.size)
        assertEquals(0f, d.carryOver, 0.0001f)
        assertEquals("+1 new · 1 gone", d.summary)
    }

    @Test
    fun `updates only earn the tilde badge, removals only the minus`() {
        val u = CronDeltaCalc.compute("- 3 tasks are waiting on review", "- 4 tasks are waiting on review")
        assertEquals("~1", u.badge)
        val r = CronDeltaCalc.compute("- a line that is gone tomorrow\n- another kept line here", "- another kept line here")
        assertEquals("−1", r.badge)
    }

    @Test
    fun `clock times and N-ago phrases are folded out of the key`() {
        val d = CronDeltaCalc.compute(
            "- Gateway healthy, last restart 2h ago at 05:12",
            "- Gateway healthy, last restart 20h ago at 11:03 PM",
        )
        assertTrue(d.same)
    }

    @Test
    fun `empty inputs are a quiet same`() {
        assertTrue(CronDeltaCalc.compute("", "").same)
        val d = CronDeltaCalc.compute("", "- something arrived in the first report ever")
        assertEquals(1, d.added.size)
    }
}
